### ISSUE TITLE
我上下滑动的时候，好像不能和游戏互动，球拍不动~~

### ISSUE THREAD

**Issue by wangqi0** [Hitomis/FunGameRefresh#5]
这个项目挺棒的，然后我导入到我的项目中去，发现不能和游戏互动，球拍 一直在初始的位置不动

**Comment by Hitomis** [comment]
请问你是什么手机，能说一下，你是具体怎么操作的么

**Comment by wangqi0** [comment]
我是小米3 note   我就是先下拉一遍  让游戏开始，然后再次下拉  也有下拉的效果，但是游戏里的球拍 和我手指的移动 互动不了。

**Comment by Hitomis** [comment]
谢谢你的反馈，我去找一部小米3 note试一试

**Comment by wangqi0** [comment]
我换了一个华为的手机  好像也不行。  
因为有的位置泛型会报错，所以我把泛型补充完整了，比方说  List<Point> pointList = new ArrayList<>();我修改成了 List<Point> pointList = new ArrayList<Point>();  。不知道有没有关系。

**Comment by wangqi0** [comment]
List<Point> pointList = new ArrayList<>();我修改成了 List<Point> pointList = new ArrayList<Point>();

**Comment by wangqi0** [comment]
List/<Point/> pointList = new ArrayList<>();我修改成了 List/<Point/> pointList = new ArrayList/<Point/>();

**Comment by wangqi0** [comment]
就是左边有泛型  右边是空的泛型。我把右边的补充起来了

**Comment by Hitomis** [comment]
额···这种写法是java8支持的，你的jdk版本应该是在1.8以下···所以不支持

**Comment by wangqi0** [comment]
但是这个应该没什么影响吧， 感觉应该是滑动的时候，位移的值没有传入进去，我也研究一下。

**Comment by wangqi0** [comment]
我已经找到原因了，监听时间里面，需要有延迟操作 Thread.sleep(2000);  不能少！谢谢哈~~~

**Comment by Hitomis** [comment]
嗯，那个是模仿后台网络请求的操作，一般都会有
