### ISSUE TITLE
代码里面下拉的实现是基于修改margin的，有没有考虑性能问题

### ISSUE THREAD

**Issue by qdrzwd** [Hitomis/FunGameRefresh#9]

**Comment by Hitomis** [comment]
@qdrzwd 谢谢你的意见，确实在性能方面比不上别的实现方式。ps:还有一点，如果游戏部分继承 SurfaceView 来做优化，会带来更好的体验。

**Comment by qdrzwd** [comment]
继承surfaceView确实会流畅一点，但是难度系数会加大。可以加入一些别的游戏，哈哈

**Comment by Hitomis** [comment]
@qdrzwd 哪一天来灵感了，会再写几种游戏的。嘿嘿
